Feat/default appbar
anniversaryArchive/archive_app pull request #10
Opened 2022-07-06 08:58 UTC by bongguma

## 🛠 주요 변경 사항 
해당 PR에서 주요 변경 사항에 대하여 작성해주세요.
- Archive 앱에 기본이 될 appbar 구현

<br/>

## 👩‍💻 Code Review 
Reviewer가 Code Review 시 중점적으로 봐야할 부분을 작성해주세요.
- 앱 첫 화면 상단에 appbar가 잘 나오는지 확인부탁드립니다 :)

<br/>

## 👨‍💻 Design Review 
Reviewer가 Design Review 시 중점적으로 봐야할 부분을 작성해주세요.

<br/>

## 📸 스크린샷
작업한 화면의 스크린샷을 첨부해주세요. (이미지 혹은 .gif)
<img src="https://user-images.githubusercontent.com/75101488/177511377-85939f08-824e-45c7-8b01-c0e61824c6df.png" width="320">

<br/>

## ✅ Test Checklist 
- [ ] 앱 첫 화면에서 Appbar가 보이는지 확인

<br/>

## 🙏 To Reviewers 
- 화면 UI 작업을 편하게 하기 위해 정말 기본적으로 AppBar 구현했습니다 ..!

2022-07-07 01:09 UTC, chochozabe approved these changes
수고하셨습니다!! 플러터 정말 신기하네용,, , ,

2022-07-07 01:09 UTC, chochozabe commented on lib/layouts/default_appbar.dart
> +  Size get preferredSize => Size.fromHeight(50);
이렇게 하면 size 라는 변수를 만드는건가요 ? 이 코드가 무엇을 뜻하는지 궁금함니당

2022-07-07 01:09 UTC, chochozabe commented on lib/screens/home_screen.dart
> +import 'package:archive/layouts/default_appbar.dart';
플러터는 파일만 import해서 그 안에 있는 함수를 사용하나여?
react는 `import { DefaultAppbar } from './archive/layouts/default_appbar.dart';` 이런 식으로 사용해서 신기해서 물어봅니당🫢

2022-07-07 01:13 UTC, hyejin-1010 requested changes
수고하셨습니다! 🙇‍♀️
`prefer_const_constructors` rule이 다 걸리네요!
해당 rule에 맞게 수정해주시거나 `analysis_options.yaml` 에서 
```
prefer_const_constructors: false
prefer_const_literals_to_create_immutables: false
prefer_const_constructors_in_immutables: false
```
를 추가해서 rule을 수정해주세요! 편하신 방법으로 선택해주시면 될 것 같습니다 〰 😊

2022-07-07 01:13 UTC, hyejin-1010 commented on lib/layouts/default_appbar.dart
> +        '${title}',
`title` 이 아니라 `'${title}'` 라고 표기한 이유가 있을까용?? 👀

2022-07-07 01:13 UTC, hyejin-1010 commented on lib/layouts/default_appbar.dart
> +        style: TextStyle(
`prefer_const_constructors` lint warning이 발생하네요! 👀

2022-07-07 01:13 UTC, hyejin-1010 commented on lib/layouts/default_appbar.dart
> +  Size get preferredSize => Size.fromHeight(50);
위에 `@override`를 붙여주세요! `annotate_overrides` lint warning 이 발생합니다!

2022-07-07 01:13 UTC, hyejin-1010 commented on lib/screens/home_screen.dart
> +    return Scaffold(
`prefer_const_constructors` lint warning이 발생하네요! 👀

2022-07-07 01:43 UTC, bongguma commented on lib/screens/home_screen.dart
> +import 'package:archive/layouts/default_appbar.dart';
네 맞습니다! 👍

2022-07-07 01:44 UTC, bongguma commented on lib/layouts/default_appbar.dart
> +  Size get preferredSize => Size.fromHeight(50);
AppBar 높이에 대한 정보를 제공해주는 Size 입니다!!

2022-07-07 01:49 UTC, chochozabe commented on lib/layouts/default_appbar.dart
> +  Size get preferredSize => Size.fromHeight(50);
그럼 저 코드를 작성하면 플러터가 높이를 설정하는 건가용?

2022-07-07 01:53 UTC, bongguma commented on lib/layouts/default_appbar.dart
> +  Size get preferredSize => Size.fromHeight(50);
네! 저 코드를 작성하면 flutter가 appbar 높이를 지정해주게 됩니다!

2022-07-07 01:56 UTC, bongguma commented on lib/layouts/default_appbar.dart
> +        '${title}',
앗 !! 그렇네요..! 제가 처음에 ${'data'} 로 테스트하다가 수정해주면서 형태를 그대로 살려준 거 같습니다..🫠 수정할게용!

2022-07-07 01:57 UTC, bongguma commented on lib/layouts/default_appbar.dart
> +  Size get preferredSize => Size.fromHeight(50);
어머 ..! 이런 ... 실 ㅅ ..를 넵 ! 알겠습니다!

2022-07-07 02:25 UTC, bongguma commented on lib/screens/home_screen.dart
> +    return Scaffold(
저 궁금한 점이 있습니다! `const`는 '변하지 않음'을 의미하고 있는데, statelessWidget을 상속 받은 build return에는 const를 써주는건가요?

2022-07-07 02:27 UTC, hyejin-1010 commented on lib/screens/home_screen.dart
> +    return Scaffold(
현재 HomeScreen의 build return 에서 변수를 사용하고 있지 않기 때문에 flutter 기본 rule 상 const 를 써줘야 한다고 warning이 나고 있는 것입니다!

2022-07-07 03:54 UTC, bongguma commented on lib/screens/home_screen.dart
> +    return Scaffold(
그럼 homeScreen 안 build Return 안에서 변수를 사용하게 되면 const는 사용되면 안되는게 맞을까요?

2022-07-07 03:54 UTC, hyejin-1010 commented on lib/screens/home_screen.dart
> +    return Scaffold(
네! 그러면 아마 Error가 날거에용

2022-07-07 03:57 UTC, bongguma commented on lib/screens/home_screen.dart
> +    return Scaffold(
네!! 답변 감사합니다! 재검토 부탁드립니다 :)

2022-07-07 07:02 UTC, hyejin-1010 approved these changes
LGTM 👍🏼

2022-07-08 17:21 UTC, kimsojung318 approved these changes
확인했습니다! 정말 어렵군요...

2022-07-11 00:56 UTC, merged