Feat/models
anniversaryArchive/archive_app pull request #11
Opened 2022-07-08 01:10 UTC by bongguma

## 🛠 주요 변경 사항 
해당 PR에서 주요 변경 사항에 대하여 작성해주세요.
- group / artist model 생성

<br/>

## 👩‍💻 Code Review 
Reviewer가 Code Review 시 중점적으로 봐야할 부분을 작성해주세요.
- model 생성 시 받아야할 데이터를 잘 정의했는지 확인 바랍니다! 또한, null-safety를 잘 사용했는지도 확인 부탁드려요!! 

<br/>

## 👨‍💻 Design Review 
Reviewer가 Design Review 시 중점적으로 봐야할 부분을 작성해주세요.

<br/>

## 📸 스크린샷
작업한 화면의 스크린샷을 첨부해주세요. (이미지 혹은 .gif)

<br/>

## ✅ Test Checklist 

- [ ] group model 생성 잘 했는지
- [ ] artist model 생성 잘 했는지

<br/>

## 🙏 To Reviewers 
- json 직렬화와 null-safety를 오랜만에 사용해 감이 다 떨어졌네요 ...:) 수정되어야할 부분 있으면 comment 부탁드립니다!

2022-07-08 01:50 UTC, hyejin-1010 requested changes
수고하셨습니다 🙇‍♀️ 
코드 보면서 필요해 보이는 것들 몇 개 Comment 남겨봤어용!!

2022-07-08 01:50 UTC, hyejin-1010 commented on lib/models/artist.dart
> +  final DateTime? updatedAt; // 마지막 업데이트 일자
updatedAt 변수는 nullable이 아닙니다!
처음 생성 시에는 createdAt 과 동일하며, 데이터가 업데이트 되었을 때 그 시각으로 업데이트해주는 것이기 때문에 `final DateTime updatedAt;`더 맞을 것 같습니다!

2022-07-08 01:50 UTC, hyejin-1010 commented on lib/models/group.dart
> +
`final List<Artist>? artists;` 가 있는 편이 좋지 않을까요? 🤔

2022-07-08 01:50 UTC, hyejin-1010 commented on lib/models/group.dart
> +  final DateTime? updatedAt;  // 마지막 업데이트 일자
이 부분도 `lib/models/artist.dart`에 단 코멘트와 동일합니다 !

2022-07-08 01:50 UTC, hyejin-1010 commented on lib/models/artist.dart
> +
`final dynamic image; // 아티스트 이미지` 가 추가될 필요가 있어보입니다🤔
```
String? get imagePath {
  if (image == null) { return null; }
  return 'https://anniversary-archive.herokuapp.com/${image['_id']}';
}
```
위와 같은 Getter도 넣어 놓으면 좋지 않을까요??
`common/config.dart`과 같이 파일을 만들어서 안에 
```
class Config {
  final String host = 'https://anniversary-archive.herokuapp.com';
}
```
server host 도 따로 빼두면 좋을 거 같군요!

2022-07-08 01:50 UTC, hyejin-1010 commented on lib/models/group.dart
> +  final DateTime debutDate;  // 데뷔일
artist model의 image 필드 관련 코멘트를 남긴 것처럼 group model 안에도 `logo` 필드가 필요할 거 같습니다 !

2022-07-08 01:52 UTC, chochozabe commented on lib/models/artist.dart
> +  final DateTime? updatedAt; // 마지막 업데이트 일자
`final DateTime? updatedAt;` 에서 ? 표시는 nullable 표시인가요 ??

2022-07-08 01:55 UTC, hyejin-1010 commented on lib/models/artist.dart
> +  final DateTime? updatedAt; // 마지막 업데이트 일자
네, 맞습니다!
default가 non-nullable 로 선언되기 때문에, nullable인 경우 ?를 붙여주어야 합니당.

2022-07-08 01:58 UTC, bongguma commented on lib/models/artist.dart
> +  final DateTime? updatedAt; // 마지막 업데이트 일자
아 ..! 처음에 생성될 때 updatedAt 안에 날짜가 들어가네요 ..! 수정해두겠습니다!

2022-07-08 02:09 UTC, bongguma commented on lib/models/group.dart
> +
🫢 맞습니다...추가해둘게요!!!

2022-07-08 07:03 UTC, bongguma commented on lib/models/artist.dart
> +
네!! 서버 호스트 따로 config에 정의해두겠습니다!!!

2022-07-08 07:06 UTC, bongguma commented on lib/models/artist.dart
> +
Image도 dynamic말고 Image 모델로 하나 만들어서 id값을 가져오는건 어떨까요?!

2022-07-09 00:43 UTC, hyejin-1010 approved these changes
수고하셨습니다! Comment만 하나 남겨놨습니다 🙇‍♀️

2022-07-09 00:43 UTC, hyejin-1010 commented on lib/common/config.dart
> +  final String host = 'https://anniversary-archive.herokuapp.com';
이 부분을 static 변수로 하면 나중에 사용할 때 생성사 선언 안하고 바로 `Config.host`와 같이 사용할 수 있어서, static 변수로 하는 게 더 좋지 않을까? 라는 생각이 듭니당! (그저 의견입니다)

2022-07-11 01:01 UTC, bongguma commented on lib/common/config.dart
> +  final String host = 'https://anniversary-archive.herokuapp.com';
아..!! 맞습니다 !!! final로 선언해야지만 생각하고 거기까지 생각하지는 못했네요.. 지금 수정해두겠습니다! config에 있는 데이터 사용 시 매번 config 선언하는 것보다 좋을 거 같습니다!

2022-07-11 03:02 UTC, chochozabe approved these changes
수고하셨습니다~ 몇가지 질문 코멘트로 남겨두었습니다!

2022-07-11 03:02 UTC, chochozabe commented on lib/models/artist.dart
> +part 'artist.g.dart';
part는 무슨 역할인가용?

2022-07-11 03:02 UTC, chochozabe commented on lib/models/group.dart
> +  final dynamic logo; // 그룹 로고 이미지
dynamic은 어떤 타입인가요!!

2022-07-11 06:44 UTC, hyejin-1010 commented on lib/models/artist.dart
> +part 'artist.g.dart';
제가 대신 답변을 드리자면, `artist.dart` 파일에는 `part 'artist.g.dart';`가 있고, `artist.g.dart` 파일에는 `part of 'artist.dart';`가 있습니다!
`part`와 `part of`를 사용하면, 여러 개의 파일이 하나의 파일인 것 처럼 처리되게 됩니다!😊

2022-07-11 06:45 UTC, hyejin-1010 commented on lib/models/group.dart
> +  final dynamic logo; // 그룹 로고 이미지
flutter에서의 `dynamic` type은 typescript의 `any` type과 비슷하다고 보시면 될 거 같습니다 !

2022-07-11 07:37 UTC, chochozabe commented on lib/models/group.dart
> +  final dynamic logo; // 그룹 로고 이미지
오호,, ts에서 any는 사용을 권장하는 타입은 아닌데 dynamic은 그렇진않나요!?

2022-07-11 07:57 UTC, hyejin-1010 commented on lib/models/group.dart
> +  final dynamic logo; // 그룹 로고 이미지
제가 기억하기로 typescript에서의 any 타입은 좀 강하게 권장되지 않는 느낌이었던 걸로 기억합니다 !
flutter에 경우에는 object 타입이 없기 때문에, dynamic 타입의 남용은 권장하지 않지만 때에 object를 dynamic을 사용해 표현하는 경우도 있습니다! 모든 걸 model로 만드는 것 또한 비효율적일 수 있기 때문입니다! (사실 이 부분은 현재 flutter를 쓰는 사람들 사이에서도 여러 의견이 나오고 있는 것으로 보입니다! 어떤 사람은 최대한 권장하지 않는다고 말하기도 하거든요🤔

2022-07-11 08:09 UTC, bongguma commented on lib/models/group.dart
> +  final dynamic logo; // 그룹 로고 이미지
모든 걸 model로 만드는 것 또한 의견이 갈린다는 건 처음 알게된 사실이네요 ..!!!

2022-07-11 08:11 UTC, kimsojung318 approved these changes
다른 분들 코멘트로 몰랐던 부분을 알게 되네요! 고생 많으셨습니다!

2022-07-11 08:11 UTC, hyejin-1010 commented on lib/models/group.dart
> +  final dynamic logo; // 그룹 로고 이미지
저는 그런 글들을 봤어서요! 구글에서 이거는 권장하지 않습니다! 라고 공표한 게 아니다 보니 의견이 나뉘는 것 같기도 합니다🤔 
`dynamic`이 찝찝하다면 아예 `String imageId;` 으로 만들어서 _id만 저장하게끔 해두는 건 어떨까요?? 👀

2022-07-11 12:20 UTC, merged

2022-07-11 12:25 UTC, bongguma commented on lib/models/group.dart
> +  final dynamic logo; // 그룹 로고 이미지
허ㄱ .. 제가 이 코멘트를 머지하고 봤네요 ..!!! 이미지를 로드하는 작업 진행 시 다시 생각해보아도 될까요!?!! 혜진님 말씀처럼 logoId로 경로를 가져오니까 logoId만 있어도 될 거 같긴 합니다! 나중에 group 모델에서 이미지 경로를 가져오는 getter도 작업해두어야겠네요 ㅠ 미리 했었으면 편리했을텐데  ,, ㅠ .. ㅠ

2022-07-11 15:02 UTC, hyejin-1010 commented on lib/models/group.dart
> +  final dynamic logo; // 그룹 로고 이미지
아닙니다 ! 나중에 시간 되실 때 작업해봐주시면 될 것 같습니당 !! 급한 부분은 아니니까요 😊